Feature/authentication
Triply-Organization/frontend pull request #16
Opened 2022-06-29 06:19 UTC by nguyendangnfq

2022-06-29 06:29 UTC, pum-khoa requested changes
![image](https://user-images.githubusercontent.com/104960618/176366603-7623ff66-f9e3-4ae2-b10f-bcfb4908d101.png)

Why login page have border-radius input but not on the register page?
It is not the same, suggest to change the same with border or without border

2022-06-29 07:37 UTC, nguyendangnfq commented
I changed it, Please check it again @pum-khoa @duyvodev

2022-06-30 02:24 UTC, pum-khoa approved these changes

2022-06-30 02:44 UTC, duyvodev approved these changes

2022-06-30 02:44 UTC, merged