fix: set up header component
Triply-Organization/frontend pull request #6
Opened 2022-06-27 10:58 UTC by duyvodev

2022-06-28 12:44 UTC, nguyendangnfq approved these changes

2022-06-29 06:33 UTC, pum-khoa requested changes

2022-06-29 06:33 UTC, pum-khoa commented on src/components/Button/Button.jsx
> +}
What is this?

2022-06-29 06:33 UTC, pum-khoa commented on src/components/Header/Button/Button.jsx
> +}
Again?

2022-06-29 06:34 UTC, pum-khoa approved these changes

2022-06-29 06:34 UTC, merged